apiVersion: apps/v1
kind: Deployment
metadata:
 name: the-deployment
 labels:
   deployment: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: demo
    spec:
      containers:
      - name: the-container
        image: docker.io/kostiscodefresh/gitops-kustomize-app:v1.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Environment Variables:"
          echo "MY_MYSQL_DB: $MY_MYSQL_DB"
          echo "SHARED_CM: $SHARED_CM"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: MY_MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: the-map-2
              key: mysqlDB
        - name: SHARED_CM
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: mysqlDB